# Generated by Django 5.1.1 on 2024-10-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('leave_requested_at', models.DateTimeField(auto_now_add=True)),
                ('leave_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=8)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='attached_files/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leaves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
