# Generated by Django 5.1.1 on 2024-10-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_requestleave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestleave',
            name='leave_requested_at',
        ),
    ]
