# Generated by Django 5.1.1 on 2024-10-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestleave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='requestleave',
            name='start_date',
            field=models.DateField(),
        ),
    ]
